[package]
name = "driver_v1"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.28"
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread", "sync"] }
uinput = "0.1.3"
wiimote-rs = "0.2.0"
